### ISSUE TITLE
[Crash] Ticking player - Game Crash When Used with Itemphysic (Forge)

### ISSUE THREAD

**Issue by Seal0220** [JDKDigital/fireproofboats#2]
When using only Fireproofboats and Itemphysic (along with its required dependency mod CreativeCore), the game crashes while boating in water. When Fireproofboats and CreativeCore are used separately (without Itemphysic), everything works normally.

crash report below:

<pre>
---- Minecraft Crash Report ----
// Don't do that.

Time: 2023-12-01 15:25:39
Description: Ticking player

java.lang.IncompatibleClassChangeError: Method 'boolean net.minecraft.world.entity.vehicle.Boat.shouldUpdateFluidWhileRiding(net.minecraft.world.level.material.FluidState, net.minecraft.world.entity.Entity)' must be Methodref constant
	at net.minecraft.world.entity.vehicle.Boat.shouldUpdateFluidWhileRiding(Boat.java:963) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:fireproofboats.mixin.json:MixinBoat,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeEntity.shouldUpdateFluidWhileBoating(IForgeEntity.java:449) ~[forge-1.20.1-47.2.16-universal.jar%23167!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.lambda$updateInWaterStateAndDoWaterCurrentPushing$9(Entity.java:1215) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.updateFluidHeightAndDoFluidPushing(Entity.java:3072) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.lambda$updateInWaterStateAndDoWaterCurrentPushing$10(Entity.java:1215) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_20074_(Entity.java:1221) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_20073_(Entity.java:1200) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:446) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:338) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:422) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2259) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:PlayerMixin,pl:mixin:A}
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Suspected Mod: 
	Fireproof Boats (fireproofboats), Version: 1.20.1-1.0.2
		Mixin class: cy.jdkdigital.fireproofboats.mixin.MixinBoat
		Target: net.minecraft.world.entity.vehicle.Boat
		at TRANSFORMER/minecraft@1.20.1/net.minecraft.world.entity.vehicle.Boat.shouldUpdateFluidWhileRiding(Boat.java:963)
Stacktrace:
	at net.minecraft.world.entity.vehicle.Boat.shouldUpdateFluidWhileRiding(Boat.java:963) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,re:classloading,pl:mixin:APP:fireproofboats.mixin.json:MixinBoat,pl:mixin:A}
	at net.minecraftforge.common.extensions.IForgeEntity.shouldUpdateFluidWhileBoating(IForgeEntity.java:449) ~[forge-1.20.1-47.2.16-universal.jar%23167!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.lambda$updateInWaterStateAndDoWaterCurrentPushing$9(Entity.java:1215) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.updateFluidHeightAndDoFluidPushing(Entity.java:3072) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.lambda$updateInWaterStateAndDoWaterCurrentPushing$10(Entity.java:1215) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_20074_(Entity.java:1221) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_20073_(Entity.java:1200) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.Entity.m_6075_(Entity.java:446) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:338) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.Entity.m_8119_(Entity.java:422) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:EntityAccessor,pl:mixin:A}
	at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2259) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:computing_frames,re:classloading,re:mixin}
	at net.minecraft.world.entity.player.Player.m_8119_(Player.java:241) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:itemphysic.mixins.json:PlayerMixin,pl:mixin:A}
-- Player being ticked --
Details:
	Entity Type: minecraft:player (net.minecraft.server.level.ServerPlayer)
	Entity ID: 210
	Entity Name: Seal0220
	Entity's Exact location: -19.06, 62.07, -22.36
	Entity's Block location: World: (-20,62,-23), Section: (at 12,14,9 in -2,3,-2; chunk contains blocks -32,-64,-32 to -17,319,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: Boat['Boat'/211, l='ServerLevel[New World]', x=-19.06, y=62.52, z=-22.36]
Stacktrace:
	at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:467) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:262) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.Connection.m_129483_(Connection.java:263) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:142) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading}
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:907) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:89) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[client-1.20.1-20230612.114412-srg.jar%23162!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 1136486432 bytes (1083 MiB) / 2550136832 bytes (2432 MiB) up to 34359738368 bytes (32768 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 7700X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 97 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 4.49
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 4060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2803
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3699
	Graphics card #1 name: AMD Radeon(TM) Graphics
	Graphics card #1 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #1 VRAM (MB): 512.00
	Graphics card #1 deviceId: 0x164e
	Graphics card #1 versionInfo: DriverVersion=31.0.14043.7000
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 4.80
	Memory slot #0 type: Unknown
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 4.80
	Memory slot #1 type: Unknown
	Virtual memory max (MB): 68759.22
	Virtual memory used (MB): 37146.00
	Swap memory total (MB): 4096.00
	Swap memory used (MB): 114.27
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx32G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['Seal0220'/210, l='ServerLevel[New World]', x=-19.06, y=62.07, z=-22.36]]
	Data Packs: vanilla, mod:forge, mod:fireproofboats, mod:creativecore, mod:itemphysic
	Enabled Feature Flags: minecraft:vanilla
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.20.1-forge-47.2.16
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.2.16.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		forge-1.20.1-47.2.16-universal.jar                |Forge                         |forge                         |47.2.16             |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		CreativeCore_FORGE_v2.11.10_mc1.20.1.jar          |CreativeCore                  |creativecore                  |2.11.10             |DONE      |Manifest: NOSIGNATURE
		ItemPhysic_FORGE_v1.7.0_mc1.20.1.jar              |ItemPhysic                    |itemphysic                    |1.7.0               |DONE      |Manifest: NOSIGNATURE
		fireproofboats-1.20.1-1.0.2.jar                   |Fireproof Boats               |fireproofboats                |1.20.1-1.0.2        |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a8e7f9e3-eeec-44dd-baff-c857d3ece6c3
	FML: 47.2
	Forge: net.minecraftforge:47.2.16
</pre>

**Comment by katubug** [comment]
I believe I am having the same crash, but without the ItemPhysic mod. I do have CreativeCore, though. This crash occurred in multiplayer when the player got into a cherry boat in the overworld:

[crash-2023-12-14_15.49.59-client.txt](https://github.com/JDKDigital/fireproofboats/files/13679194/crash-2023-12-14_15.49.59-client.txt)

**Comment by JaisDK** [comment]
can you check with this build?

unzip and replace the 1.0.2 mod file with this one
[fireproofboats-1.20.1-1.0.3.zip](https://github.com/JDKDigital/fireproofboats/files/13683404/fireproofboats-1.20.1-1.0.3.zip)

**Comment by miner90027** [comment]
I am also experiencing this issue. I have the Create mod installed which requires the Creative Core dependancy. 
Interestingly the game only crashes when I get in a boat that is not included in this modpack.
[crash-2023-12-16_15.37.35-client.txt](https://github.com/JDKDigital/fireproofboats/files/13694389/crash-2023-12-16_15.37.35-client.txt)


Replacing the 1.0.2 mod file with 1.0.3 seems to have fixed the issue. Please update the Curseforge Mod page for this mod with the new mod file as soon as possible.

**Comment by JaisDK** [comment]
it's uploaded

**Comment by VoidLeech** [comment]
Version 1.0.3 is currently not available on Modrinth.
